CREATE TABLE IF NOT EXISTS task(
    task_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    description TEXT,
    priority int CHECK (priority > 0 AND priority < 6),
    date timestamp without time zone NOT NULL,
    stage text not null,
    user_id int REFERENCES users(user_id) ON DELETE CASCADE,
    count_observers int,
    accepted int
);

CREATE INDEX IF NOT EXISTS task_id_index ON task(task_id);
CREATE INDEX IF NOT EXISTS task_date_index ON task(date);
CREATE INDEX IF NOT EXISTS task_name_index ON task(name);
CREATE INDEX IF NOT EXISTS task_stage_index ON task(stage);
