CREATE TABLE IF NOT EXISTS token(
  token_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int REFERENCES users(user_id),
  token text UNIQUE,
  revoked bool,
  expired bool
);

CREATE INDEX IF NOT EXISTS index_token ON token(token);